version: 0.0
os: linux
files:
  - source: /files/gunicorn.service
    destination: /etc/systemd/system/
  - source: /
    destination: /home/ubuntu/ChatApp-Django
permissions:
  - object: /home/ubuntu/ChatApp-Django
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/installDependecies.sh
      timeout: 300
      runas: root
    - location: scripts/startgunicorn.sh
      timeout: 300
      runas: ubuntu

